library:
  source-dirs: src
tests:
  Chess-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chess
maintainer: luminiscental01@gmail.com
dependencies:
- parsec
- bytestring
- tasty
- tasty-hunit
- containers
- array
- base >= 4.7 && < 5
name: Chess
version: 0.1.0.0
extra-source-files:
- README.md
author: Luminiscental
github: Luminiscental/Chess
executables:
  Chess-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chess
description: Please see the README on GitHub at <https://github.com/Luminiscental/Chess#readme>
